services:
  - type: web
    name: ratham-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    branches: 
      - main
    runtime: node 18 # Specify Node.js version if needed
    envVars:
      - key: DB_HOST
        value: your-database-host
      - key: DB_USER
        value: your-database-username
      - key: DB_PASS
        value: your-database-password
      - key: DB_NAME
        value: your-database-name
      - key: TWILIO_ACCOUNT_SID
        value: your-twilio-account-sid
      - key: TWILIO_AUTH_TOKEN
        value: your-twilio-auth-token
      - key: TWILIO_PHONE_FROM
        value: your-twilio-phone-from
      - key: TWILIO_PHONE_TO
        value: your-twilio-phone-to